# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 747ff6a6fc8f0fbd61388303385a238f41b974eae6b496375ff713b4d7a26058f91dc44be70aea1cc42fa7ae50ef805cea9282c688fd5501e39bb88724bf04af

test:
  secret_key_base: 00f668f47855377555a07bcca0f9729faa1cd5c7a4759a17f3262f9639e9eb4b06d14a0e7b981c91a4a26237731910f535b2f80a43969d4981c50878add7c132

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
